import { Inter } from "next/font/google";
import "./globals.css"; //este esta cargando el css globa osea que si quiero cambiar algo para todas las paginas tendria que modificar en global.css

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
